audit_header: false
title:
description: >-
  Ben Taylor, a top Real Estate Agent in -- MARKET --, shares his/her own
  internal real estate agent training for free. His/Her Real Estate Training,
  Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: 'http://kwuk.com/careers.html'
  - title: Events
    url:
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
client:
  name: Ben Taylor
  title:
  license_number:
  about_markdown: >
    “Welcome to Keller Williams, a worldwide revolution in estate agency and the
    UK’s most personal property service.” - <strong>Ben Taylor, Managing
    Director, Keller Williams UK</strong>


    Keller Williams adopts a different approach to estate agency – we go the
    extra mile to sell your property. Here you will have one dedicated agent who
    will see the transaction through from start to finish. To us, service is
    paramount. A crucial difference is that our agents are their own bosses – so
    they are driven to complete sales transactions. You will notice the
    difference.
  market:
  brand: Keller Williams
  brokerage:
  address:
  phone: +44 207 078 3939
  phone_type:
  phone2:
  phone2_type:
  email: ben.taylor@kwuk.com
  url: 'http://kwuk.com'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/KWUK2013'
  linkedin_url: 'https://www.linkedin.com/company/keller-williams-uk'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UCWIA-CLRIxQLxJ5jEDPuhVw'
  twitter_url: 'https://twitter.com/thekwuk'
  instagram_url: 'https://www.instagram.com/bentaylorcoaching/'
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'